---
version: '3'

services:

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - 8991:8080
    volumes:
      - ccd-docker-wiremock-data:/home/wiremock
      - ../libs:/var/wiremock/extensions
    command:
      --extensions uk.gov.hmcts.reform.iadevtools.wiremock.WiremockResponseTransformer

  ccd-user-profile-api:
    image: hmctspublic.azurecr.io/ccd/user-profile-api:latest
    environment:
      USER_PROFILE_DB_HOST: ccd-shared-database-v11
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "${DB_USE_SSL}"
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      JAVA_TOOL_OPTIONS: -Xmx384m
    ports:
      - 4453:4453
    depends_on:
      - ccd-shared-database-v11
    links:
      - ccd-shared-database-v11
      - service-auth-provider-api

  ccd-definition-store-api:
    image: hmctspublic.azurecr.io/ccd/definition-store-api:latest
    environment:
      DEFINITION_STORE_DB_HOST: ccd-shared-database-v11
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_TX_TIMEOUT_DEFAULT: 60
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,aac_manage_case_assignment
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://sidam-api:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
      JAVA_TOOL_OPTIONS: -Xmx384m
    ports:
      - 4451:4451
    depends_on:
      - ccd-shared-database-v11
      - ccd-user-profile-api
      - sidam-api
    links:
      - ccd-shared-database-v11
      - ccd-user-profile-api
      - sidam-api
      - service-auth-provider-api

  ccd-data-store-api:
    image: hmctspublic.azurecr.io/ccd/data-store-api:latest
    environment:
      DATA_STORE_DB_HOST: ccd-shared-database-v11
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,fpl_case_service,ccd_data,ccd_ps,iac,em_stitching_api,em_gw,em_ccd_orchestrator,aac_manage_case_assignment,ccd_case_document_am_api,xui_webapp,am_role_assignment_service
      CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: ccd_gw,iac,ia,aac_manage_case_assignment,xui_webapp
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_API_BASE_URL: http://sidam-api:5000
      IDAM_OIDC_URL: http://sidam-api:5000
      IDAM_USER_URL: http://sidam-api:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
      ELASTIC_SEARCH_CASE_INDEX_NAME_FORMAT: '%s_cases'
      ELASTIC_SEARCH_CASE_INDEX_TYPE: _doc
      IDAM_CLIENT_ID: ccd_gateway
      IDAM_CLIENT_REDIRECT_URI: "http://localhost:3002/oauth2/callback"
      IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: OOOOOOOOOOOOOOOO
      IDAM_DATA_STORE_SYSTEM_USER_USERNAME: "${CCD_SYSTEM_USERNAME}"
      IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: "${CCD_SYSTEM_PASSWORD}"
      CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api:4455
      ROLE_ASSIGNMENT_URL: "${ROLE_ASSIGNMENT_URL:-http://am-role-assignment-service:4096}"
      JAVA_TOOL_OPTIONS: -Xmx384m
    ports:
      - 4452:4452
    depends_on:
      - ccd-shared-database-v11
      - ccd-user-profile-api
      - ccd-definition-store-api
      - sidam-api
    links:
      - ccd-shared-database-v11
      - ccd-user-profile-api
      - ccd-definition-store-api
      - sidam-api
      - service-auth-provider-api

  ccd-case-document-am-api:
    build:
      context: .
    image: "${CCD_CASE_DOCUMENT_AM_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/case-document-am-api:${CCD_CASE_DOCUMENT_AM_API_TAG:-latest}"
    container_name: ccd-case-document-am-api
    environment:
      CASE_DOCUMENT_AM_API_S2S_SECRET: "AAAAAAAAAAAAAAAA"
      CASE_DOCUMENT_S2S_AUTHORISED_SERVICES: ccd_case_document_am_api,ccd_gw,xui_webapp,ccd_data,bulk_scan_processor,iac,ia,stitching-api,rpa-em-ccd-orchestrator
      DM_STORE_BASE_URL: http://dm-store:8080
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api:4452
      IDAM_OIDC_URL: http://sidam-api:5000
      IDAM_API_URL: http://sidam-api:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-case-document-am-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      DOCUMENT_TTL: 3600000
    ports:
      - 4455:4455
    depends_on:
      - ccd-data-store-api
      - dm-store
      - service-auth-provider-api

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_CCD_ADMIN: "${IDAM_KEY_CCD_ADMIN}"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "${IDAM_KEY_FPL_CASE_SERVICE}"
      MICROSERVICEKEYS_XUI_WEBAPP: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_IAC: "${IDAM_KEY_IAC}"
      MICROSERVICEKEYS_AAC_MANAGE_CASE_ASSIGNMENT: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CCD_CASE_DOCUMENT_AM_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_EM_GW: "${IDAM_KEY_EM_GW}"
      MICROSERVICEKEYS_EM_STITCHING_API: "${IDAM_KEY_EM_STITCHING_API}"
      MICROSERVICEKEYS_EM_CCD_ORCHESTRATOR: "${IDAM_KEY_EM_CCD_ORCHESTRATOR}"
      MICROSERVICEKEYS_AM_ROLE_ASSIGNMENT: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PAYMENT_APP: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PAYMENTOUTCOME_WEB: "AAAAAAAAAAAAAAAA"
      TESTING_SUPPORT_ENABLED: "true"
      JAVA_TOOL_OPTIONS: -Xmx384m

  ia-timed-event-service:
    image: hmctspublic.azurecr.io/ia/timed-event-service:latest
    ports:
      - 8095:8095
    depends_on:
      - ccd-shared-database-v11
      - ccd-data-store-api
      - sidam-api
      - service-auth-provider-api
    links:
      - ccd-shared-database-v11
      - ccd-data-store-api
      - sidam-api
      - service-auth-provider-api
    environment:
      IDAM_URL: http://sidam-api:5000
      S2S_URL: http://service-auth-provider-api:8080
      CCD_URL: http://ccd-data-store-api:4452
      POSTGRES_HOST: ccd-shared-database-v11
      POSTGRES_PORT: 5432
      IA_IDAM_CLIENT_ID: "${IA_IDAM_CLIENT_ID}"
      IA_IDAM_SECRET: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IA_IDAM_REDIRECT_URI: "${IA_IDAM_REDIRECT_URI}"
      IA_SYSTEM_USERNAME: "${IA_SYSTEM_USERNAME}"
      IA_SYSTEM_PASSWORD: "${IA_SYSTEM_PASSWORD}"
      IA_S2S_MICROSERVICE: "${IA_S2S_MICROSERVICE}"
      IA_S2S_SECRET: "${IDAM_KEY_IAC}"
      IA_S2S_AUTHORIZED_SERVICES: "${IA_S2S_MICROSERVICE}"
      SPRING_PROFILES_ACTIVE: test

  am-role-assignment-service:
    image: "${AM_ROLE_ASSIGNMENT_SERVICE_USE_LOCAL-hmctspublic.azurecr.io/}am/role-assignment-service:${AM_ROLE_ASSIGNMENT_SERVICE_TAG:-latest}"
    environment:
      ROLE_ASSIGNMENT_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database-v11}"
      ROLE_ASSIGNMENT_DB_NAME: role_assignment
      ROLE_ASSIGNMENT_DB_PORT: 5432
      ROLE_ASSIGNMENT_DB_USERNAME: "${DB_USERNAME}"
      ROLE_ASSIGNMENT_DB_PASSWORD: "${DB_PASSWORD}"
      ROLE_ASSIGNMENT_DB_OPTIONS:
      AM_ROLE_ASSIGNMENT_SERVICE_SECRET: "AAAAAAAAAAAAAAAA"
      LD_SDK_KEY:
      ROLE_ASSIGNMENT_IDAM_KEY:
      ROLE_ASSIGNMENT_TOKEN_SECRET:
      ROLE_ASSIGNMENT_S2S_AUTHORISED_SERVICES: ccd_gw,am_role_assignment_service,am_org_role_mapping_service,wa_task_management_api,xui_webapp,ccd_data,iac
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://sidam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://sidam-api:5000}/o"
      OIDC_ISSUER_URL: "${IDAM_STUB_SERVICE_NAME:-http://sidam-api:5000}/openam/oauth2/hmcts"
      ROLE_ASSIGNMENT_IDAM_CLIENT_ID: am_role_assignment
      ROLE_ASSIGNMENT_IDAM_CLIENT_SECRET: am_role_assignment_secret
      ROLE_ASSIGNMENT_IDAM_ADMIN_USERID: role.assignment.admin@gmail.com
      ROLE_ASSIGNMENT_IDAM_ADMIN_PASSWORD: "${AM_ROLE_AADMINGMENT_ADMIN_PWD:-Pa55word11}"
      ROLE_ASSIGNMENT_IDAM_ADMIN_SCOPE: profile openid roles search-user
      CCD_DATA_STORE_URL: http://ccd-data-store-api:4452
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      REFORM_SERVICE_NAME: am-role-assignment-service
      REFORM_TEAM: am
      REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 4096:4096
    depends_on:
      - ccd-shared-database-v11
      - ccd-data-store-api
      - sidam-api
      - service-auth-provider-api


  manage-case-assignment:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/aac/manage-case-assignment:latest
    ports:
      - 4454:4454
    environment:
      IDAM_OIDC_URL: http://sidam-api:5000
      IDAM_API_URL: http://sidam-api:5000
      IDAM_CLIENT_ID: ccd_gateway
      IDAM_CLIENT_SECRET: OOOOOOOOOOOOOOOO
      IDAM_CLIENT_REDIRECT_URL: http://localhost:3002/oauth2/callback
      IDAM_CAA_USERNAME: "caa-caseworker@fake.hmcts.net"
      IDAM_CAA_PASSWORD: "London21"
      IDAM_NOC_APPROVER_USERNAME: "approver-noc@fake.com"
      IDAM_NOC_APPROVER_PASSWORD: "Pa55word11"
      IDAM_SYSTEM_USER_USERNAME: "caa-caseworker@fake.hmcts.net"
      IDAM_SYSTEM_USER_PASSWORD: "London21"
      IDAM_URL: http://sidam-api:5000
      S2S_URL: http://service-auth-provider-api:8080
      MANAGE_CASE_S2S_KEY: "AAAAAAAAAAAAAAAA" # use aat key from vault
      MANAGE_CASE_S2S_AUTHORISED_SERVICES: ccd_gw,xui_webapp,ccd_data,iac
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api:4452
      CCD_DATA_STORE_ALLOWED_SERVICE: ccd_gw
      CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api:4451
      MCA_DS_PROXY_URLS_ALLOWED_LIST: /searchCases.*,/internal/searchCases.*,/internal/cases.*
      MCA_DEF_STORE_PROXY_URLS_ALLOWED_LIST: /api/display/challenge-questions.*
      MCA_CONDITIONAL_APIS_CASE_ASSIGNMENTS_ENABLED: "true"
      PRD_HOST: http://wiremock:8080
      NOTIFY_MCA_API_KEY: "notify-test-api-key"
      JAVA_TOOL_OPTIONS: -Xmx384m

  ia-home-office-mock-api:
    image: hmctspublic.azurecr.io/ia/home-office-mock-api:latest
    ports:
      - 8098:8098

  smtp-server:
    image: mailhog/mailhog

  ccd-shared-database-v11:
    build: ../database-v11
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432
    volumes:
      - ccd-docker-ccd-shared-database-data-v11:/var/lib/postgresql/data

volumes:
  ccd-docker-ccd-shared-database-data-v11:
  ccd-docker-wiremock-data:
