---
version: '3'

services:

  stitching-api:
    image: hmctspublic.azurecr.io/em/stitching:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stitching-db:5432/emstitch
      SPRING_DATASOURCE_USERNAME: emstitch
      SPRING_DATASOURCE_PASSWORD: emstitch
      S2S_BASE_URI: http://service-auth-provider-api:8080
      IDAM_API_BASE_URI: http://sidam-api:5000
      ENABLE_LIQUIBASE: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      DM_STORE_APP_URL: http://dm-store:4506
      DOCMOSIS_ACCESS_KEY: "${DOCMOSIS_ACCESS_KEY}"
      S2S_NAMES_WHITELIST: jui_webapp,em_ccd_orchestrator,em_gw,iac
      JAVA_OPTS: -Xmx512m
    depends_on:
      - stitching-db
      - dm-store
    links:
      - stitching-db
      - dm-store
    ports:
      - 4630:8080

  stitching-db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=emstitch
      - POSTGRES_USER=emstitch
      - POSTGRES_PASSWORD=emstitch
      
  rpa-em-ccd-orchestrator:
    image: hmctspublic.azurecr.io/em/ccd-orchestrator:latest
    environment:
      SERVER_PORT: 8060
      IDAM_API_BASE_URI: http://sidam-api:5000
      S2S_BASE_URI: http://service-auth-provider-api:8080
      EM_STITCHING_API_URL: http://stitching-api:8080
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      # these environment variables are used by java-logging library
      JSON_CONSOLE_PRETTY_PRINT: "false"
      ROOT_LOGGING_LEVEL:
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: rpa-em-ccd-orchestrator
      REFORM_TEAM: em-ccd-orchestrator
      REFORM_ENVIRONMENT: docker
      JAVA_OPTS: -Xmx486m
    ports:
      - 4623:8060
