---
version: '3'

services:

  stitching-api:
    image: hmctspublic.azurecr.io/em/stitching:latest
    restart: on-failure
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stitching-db:5432/emstitch
      SPRING_DATASOURCE_USERNAME: emstitch
      SPRING_DATASOURCE_PASSWORD: emstitch
      S2S_BASE_URI: http://service-auth-provider-api:8080
      IDAM_API_BASE_URI: http://sidam-api:5000
      OPEN_ID_API_BASE_URI: http://sidam-api:5000/o
      ENABLE_LIQUIBASE: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      DM_STORE_APP_URL: http://dm-store:8080
      DOCMOSIS_ENDPOINT: "${EM_DOCMOSIS_CONVERT_ENDPOINT}"
      DOCMOSIS_RENDER_ENDPOINT: "${EM_DOCMOSIS_RENDER_ENDPOINT}"
      DOCMOSIS_ACCESS_KEY: "${DOCMOSIS_ACCESS_KEY}"
      S2S_NAMES_WHITELIST: jui_webapp,em_ccd_orchestrator,em_gw,iac
      ROOT_LOGGING_LEVEL: WARN
      JAVA_TOOL_OPTIONS: -Xmx384m
    depends_on:
      - sidam-api
      - stitching-db
      - dm-store
    links:
      - service-auth-provider-api
      - sidam-api
      - stitching-db
      - dm-store
    ports:
      - 4630:8080
    # it is needed to generate bundle cover page - there is an issue with VPN dns settings and docker environment
    # ping docmosis.aat.platform.hmcts.net to get latest IP if there is a change
    extra_hosts:
      - "docmosis.aat.platform.hmcts.net:10.10.161.121"

  stitching-db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=emstitch
      - POSTGRES_USER=emstitch
      - POSTGRES_PASSWORD=emstitch
      
  rpa-em-ccd-orchestrator:
    image: hmctspublic.azurecr.io/em/ccdorc:latest
    restart: on-failure
    environment:
      SERVER_PORT: 8080
      CCD_DATA_API_URL: http://ccd-data-store-api:4452
      IDAM_API_BASE_URI: http://sidam-api:5000
      OPEN_ID_API_BASE_URI: http://sidam-api:5000/o
      S2S_BASE_URI: http://service-auth-provider-api:8080
      EM_STITCHING_API_URL: http://stitching-api:8080
      CALLBACK_DOMAIN: rpa-em-ccd-orchestrator
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ENABLE_LIQUIBASE: "true"
      # these environment variables are used by java-logging library
      JSON_CONSOLE_PRETTY_PRINT: "false"
      ROOT_LOGGING_LEVEL: WARN
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: rpa-em-ccd-orchestrator
      REFORM_TEAM: em-ccd-orchestrator
      REFORM_ENVIRONMENT: docker
      JAVA_TOOL_OPTIONS: -Xmx384m
    ports:
      - 4623:8080
    depends_on:
      - sidam-api
      - stitching-api
    links:
      - service-auth-provider-api
      - sidam-api
      - stitching-api
      - ccd-data-store-api
