---
version: '3'

services:

  ccd-api-gateway:
    image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
    container_name: ccd-api-gateway-web
    environment:
      IDAM_BASE_URL: http://sidam-simulator:5000
      IDAM_USER_URL: http://sidam-simulator:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: http://sidam-simulator:5000/session/:token
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_OAUTH2_TOKEN_ENDPOINT: http://sidam-simulator:5000/oauth2/token
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      ADDRESS_LOOKUP_TOKEN: "${ADDRESS_LOOKUP_TOKEN}"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api

