---
version: '3'

services:

  payments-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/payment/api:latest
    environment:
      LAUNCH_DARKLY_SDK_KEY: "${LAUNCH_DARKLY_SDK_KEY_FEE_N_PAY_DEMO}"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://service-auth-provider-api:8080
      AUTH_IDAM_CLIENT_BASEURL: http://sidam-simulator:5000
      AUTH_REF_DATA_BASEURL: http://wiremock:8080
      ASB_CONNECTION_STRING: "${AZURE_SERVICE_BUS_CONNECTION_STRING}"
      IDAM_S2S_AUTH_URL: http://service-auth-provider-api:8080
      GOV_PAY_URL: https://publicapi.payments.service.gov.uk/v1/payments
      FEES_REGISTER_URL: http://wiremock:8080
      RD_LOCATION_BASE_URL: http://wiremock:8080
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "*"
      SPRING_MAIL_PORT: "25"
      SPRING_MAIL_HOST: "mta.reform.hmcts.net"
      CARD_PAYMENTS_REPORT_SCHEDULER_ENABLED: "false"
      GOV_PAY_AUTH_KEY_IAC: "${GOV_PAY_IAC_KEY}"
      GOV_PAY_AUTH_KEY_CMC: "${GOV_PAY_CMC_KEY}"
      IDAM_S2S_AUTH_TOTP_SECRET: "AAAAAAAAAAAAAAAA"
      IDAM_S2S_AUTH_MICROSERVICE: "payment_app"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://payments-db:5432/payment"
      SPRING_DATASOURCE_USERNAME: "payment"
      SPRING_DATASOURCE_PASSWORD: "payment"
      SPRING_LIQUIBASE_ENABLED: "true"
      AZURE_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: "dummy"
      TRUSTED_S2S_SERVICE_NAMES: "cmc,iac,xui_webapp,payment_app,paymentoutcome_web"
      SPRING_PROFILES_ACTIVE: "${PAYMENTS_API_PROFILE:-liberataMock}"
    ports:
      - 8083:8080
    depends_on:
      - payments-db
      - wiremock
    links:
      - sidam-simulator
      - wiremock
      - service-auth-provider-api

  payments-db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: "payment"
      POSTGRES_PASSWORD: "payment"
      POSTGRES_DB: "payment"
    ports:
      - 5183:5432
