---
version: '3'

services:

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:latest
    environment:
      AppInsightsInstrumentationKey: fake
      STRATEGIC_SERVICE_URL: http://wiremock:8080
      IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
      REFORM_SERVICE_NAME: sidam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m
    ports:
      - 3501:8080
    links:
      - wiremock
    depends_on:
      - wiremock

volumes:
  ccd-docker-idam-shared-database-data: